services:
  parrot-refactoring:
    build: .
    container_name: ipc25-parrot
    user: ${UID}:${GID}
    volumes:
      - .:/srv/workshop-ipc25-munich/refactoring/parrot:delegated
    environment:
      XDEBUG_MODE: debug
      XDEBUG_SESSION: PHPSTORM
