services:
  guess-number-tdd:
    build: .
    container_name: ipc25-guess-number
    user: ${UID}:${GID}
    volumes:
      - .:/srv/workshop-ipc25-munich:delegated
    environment:
      XDEBUG_MODE: debug
      XDEBUG_SESSION: PHPSTORM
